version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /docker-creds/username
    DOCKER_REGISTRY_PASSWORD: /docker-creds/password
phases:
  install:
    runtime-versions:
      python: 3.12
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  build:
    commands:
      build:
  commands:
    - docker build -t my-app .
    - docker tag my-app:latest $DOCKER_REGISTRY_USERNAME/my-app:latest
post_build:
  commands:
    - docker push $DOCKER_REGISTRY_USERNAME/my-app:latest

  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'
  # base-directory: codepipeline-demo
  # name: dev-artifacts
  # discard-paths: no

